app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
supprimeP:
    pattern: /supprimer/
    defaults: { _controller: AppBundle:Controller:PanierController }
    requirements:
        _method: POST
