<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{    
    public function findPaginated($page){  
        
        $this->em = $this->getEntityManager();  
        $qb = $this->createQueryBuilder('b');
        
        $qb->select('b')
                ->addSelect('r')
                ->addSelect('a')
                ->leftJoin('b.rel', 'r')
                ->leftJoin('r.authors', 'a');
                        
        $query = $qb->getQuery();
        
        $numPerPage = 10;
        $query->setMaxResults($numPerPage);
        $query->setFirstResult( ($page-1) * $numPerPage );
        $result = $query->getResult();
        
        $paginationResults = array();
        
        //les actualités
        $paginationResults["data"] = $result;
        //affichage des infos sur les résultats
        $paginationResults['nowShowingMin'] = ($page-1) * $numPerPage + 1;
        $paginationResults['nowShowingMax'] = $paginationResults['nowShowingMin'] + count($result) - 1;
        //nombre total possible
        $paginationResults["total"] = $qb->select("COUNT(b)")->getQuery()->getSingleScalarResult();
        //liens numériques
        $numPagesDiff = 2;
        $lastPage = ceil($paginationResults["total"] / $numPerPage);
        $paginationResults['numLinkMin'] = ($page - $numPagesDiff < 1) ? 1 : $page - $numPagesDiff;
        $paginationResults['numLinkMax'] = ($page + $numPagesDiff >= $lastPage) ? $lastPage : $page + $numPagesDiff;
        //page précédente ?
        $paginationResults["prevPage"] = ($page <= 1) ? false : $page-1;
        $paginationResults["nextPage"] = ($page >= $lastPage) ? false : $page+1;

        //dump($paginationResults);
        return $paginationResults;
    }
    
}
