<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
     public function findCartByUser($user){
         
         $qb = $this->createQueryBuilder('c');
        
        $qb->select('c')
                ->addSelect('u')
                ->leftJoin('c.user', 'u')
                ->where('c.user ='.$user->getId());
                
        
            $query = $qb->getQuery();
        
            return $query->getResult();
         
         
     }
    
    
    
    
    
}
