<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Pickup_spotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pickup_spotRepository extends EntityRepository
{
}
