<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Rel_BookAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rel_BookAuthorRepository extends EntityRepository
{
}
