<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Relation_BookCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Relation_BookCartRepository extends EntityRepository
{
}
